### ISSUE TITLE
Mapping

### ISSUE THREAD

**Issue by sneakythr0ws** [FelixMarschall/SmartHomeProcessMining#1]
Hi! Nice job!
How are you going to map the attributes(`case:concept:name`, `concept:name`, `org:resource`)?

Do you plan to find new automations?
Did you already find something useful?

**Comment by f-marschall** [comment]
Hey,
thanks for your interest!

For example:
- `case:concept:name` timespan of a single day (case ID)
- `concept:name` device message and state (activity name)
- `org:resource` I couldn't map it because I couldn't differentiate between users in my environment :)


`case:concept:name` is a unique identifier for a case, which can be challenging to set in a multi-user environment. To overcome this challenge, it is recommended to select time intervals when only one person generates events, such as early mornings (between 6:00-7:00), in order to ensure the uniqueness of the case identifier.

Two examples of process model extraction: 
- [On two weeks data with noise](https://github.com/FelixMarschall/Logbook-ProcessDiscovery/blob/main/approach_02_including_state.ipynb)
- [Single day data with less noise](https://github.com/FelixMarschall/Logbook-ProcessDiscovery/blob/main/approach_02_including_state_AIFB_singleDay.ipynb)

I have not found any new automations in my smart home, but I have been able to time the existing automations better and visual their dependencies.

Nevertheless, find possible automations and habit extraction is a hot topic in research, which will probably get more attention in the future.

Thanks for your question!
